### PR TITLE
Flaskserver

### PR DESCRIPTION
**Pull request by tug73060**

### CODE REVIEW

**Review by BareBeaverBat — CHANGES_REQUESTED** [review]
Several files/folders were added here which really shouldn't be in version control.
Also, the other project folders seem to have been moved inside of the middleman server's project folder, which isn't what we've been doing. Instead, we've been having the different components' project folders as separate folders that're all at the root level in the repository.
Please explain why the backend server component's project folder should be moved inside of the middleman server component's project folder or undo the move

**Review by BareBeaverBat — CHANGES_REQUESTED** [review]
Also, please remove the .DS_Store files and the "_ _ pycache _ _" folders from version control. In the same vein, please also add those files to a .gitignore file at the repository's root

**Comment by tug73060** [comment]
I changed the organization of the repository. Please take a look.

**Review by BareBeaverBat — APPROVED** [review]

**Review by BareBeaverBat — CHANGES_REQUESTED** [review]
Wait! Something went wrong somewhere with the Backend package, and most of its files are deleted!

**Review by BareBeaverBat — APPROVED** [review]

**Pull request merged**
